server:
  port: 8090

spring:
  cloud:
    gateway:
      default-filters:
        - AddResponseHeader=source, zq
      routes:
        - id: api_route
          uri: http://localhost:8123
          predicates:
            - Path=/api/name/**

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace
dubbo:
  application:
    name: dubbo-api-platform-backend-provider
    qos:
      enable: false
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    address: nacos://localhost:8848


